[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/mad-start/jnotes/blob/main/pytorch_lab.ipynb)

In [3]:
# !pip install torch torchvision torchaudio

In [1]:
import torch
torch.manual_seed(1)

In [18]:
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

tensor([1., 2., 3.])


In [19]:
M_data = [[1., 2., 3.], [4., 5., 6.]]
M = torch.tensor(M_data)
print(M)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [21]:
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


### Tensor Manipulation

In [24]:
V[0].item()

1.0

In [36]:
T[1, 0]

tensor([5., 6.])

In [45]:
T = torch.randn((3,4,5))

In [52]:
T[:, 3, 1]

tensor([-1.4726,  0.9698, -0.7391])

In [55]:
T

tensor([[[ 0.0713, -0.5037,  0.8034,  1.1834,  0.0237],
         [ 1.1120, -0.9464,  1.6345, -0.3461,  0.2707],
         [-1.3579, -0.9611, -0.3545,  1.3506,  1.8432],
         [-1.2497, -1.4726, -1.4529,  0.2563, -0.7528]],

        [[-0.4571, -0.2152,  1.5451, -0.3932,  1.4463],
         [-1.1437,  0.7888, -0.6769,  0.2527, -0.6618],
         [ 1.3849, -0.1820, -0.0223, -1.5084, -2.7273],
         [-0.8595,  0.9698,  0.2922,  0.5750,  0.4776]],

        [[ 0.2996, -1.0239,  1.0269, -0.1925,  1.3378],
         [-0.0713, -1.6469,  0.8410, -0.3101, -1.0481],
         [-0.9334,  0.2453,  0.3469,  2.5516, -0.8072],
         [ 3.3628, -0.7391,  0.2280,  0.9885, -2.1413]]])

In [62]:
torch.cat([T, T[:, [1], :]], 1)

tensor([[[ 0.0713, -0.5037,  0.8034,  1.1834,  0.0237],
         [ 1.1120, -0.9464,  1.6345, -0.3461,  0.2707],
         [-1.3579, -0.9611, -0.3545,  1.3506,  1.8432],
         [-1.2497, -1.4726, -1.4529,  0.2563, -0.7528],
         [ 1.1120, -0.9464,  1.6345, -0.3461,  0.2707]],

        [[-0.4571, -0.2152,  1.5451, -0.3932,  1.4463],
         [-1.1437,  0.7888, -0.6769,  0.2527, -0.6618],
         [ 1.3849, -0.1820, -0.0223, -1.5084, -2.7273],
         [-0.8595,  0.9698,  0.2922,  0.5750,  0.4776],
         [-1.1437,  0.7888, -0.6769,  0.2527, -0.6618]],

        [[ 0.2996, -1.0239,  1.0269, -0.1925,  1.3378],
         [-0.0713, -1.6469,  0.8410, -0.3101, -1.0481],
         [-0.9334,  0.2453,  0.3469,  2.5516, -0.8072],
         [ 3.3628, -0.7391,  0.2280,  0.9885, -2.1413],
         [-0.0713, -1.6469,  0.8410, -0.3101, -1.0481]]])

In [ ]:
T.reshape()

In [75]:
T.view()

tensor([[[ 0.0713, -0.5037,  0.8034,  1.1834,  0.0237],
         [ 1.1120, -0.9464,  1.6345, -0.3461,  0.2707],
         [-1.3579, -0.9611, -0.3545,  1.3506,  1.8432],
         [-1.2497, -1.4726, -1.4529,  0.2563, -0.7528]],

        [[-0.4571, -0.2152,  1.5451, -0.3932,  1.4463],
         [-1.1437,  0.7888, -0.6769,  0.2527, -0.6618],
         [ 1.3849, -0.1820, -0.0223, -1.5084, -2.7273],
         [-0.8595,  0.9698,  0.2922,  0.5750,  0.4776]],

        [[ 0.2996, -1.0239,  1.0269, -0.1925,  1.3378],
         [-0.0713, -1.6469,  0.8410, -0.3101, -1.0481],
         [-0.9334,  0.2453,  0.3469,  2.5516, -0.8072],
         [ 3.3628, -0.7391,  0.2280,  0.9885, -2.1413]]])

In [86]:
x = torch.tensor([1., 2., 3.], requires_grad=True)

In [87]:
y = torch.tensor([4., 5., 6.], requires_grad=True)

In [109]:
z = x+y+x

In [110]:
print(z)

tensor([ 6.,  9., 12.], grad_fn=<AddBackward0>)


In [111]:
s = z.sum()

In [95]:
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21., grad_fn=<SumBackward0>)


In [108]:
x

tensor([1., 2., 3.], requires_grad=True)

In [99]:
with torch.no_grad()

tensor([2., 2., 2.])
